config/routes.rb
Rails.application.routes.draw do
  resources :material_brands
  resources :condition_details
  resources :templates
  resources :designs
  resources :colors
  resources :clothing_brands

  root 'main#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/design.rb
class Design < ApplicationRecord
end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
  before_action :set_design, only: [:show, :edit, :update, :destroy]

  # GET /designs
  def index
    @designs = Design.all
  end

  # GET /designs/1
  def show
    respond_to do |format|
      format.html { }
      format.json { render json: @design }
    end
  end

  # GET /designs/new
  def new
    @design = Design.new
  end

  # GET /designs/1/edit
  def edit
  end

  # POST /designs
  def create
    @design = Design.new(design_params)

    if @design.save
      redirect_to @design, notice: 'Design was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /designs/1
  def update
    if @design.update(design_params)
      redirect_to @design, notice: 'Design was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /designs/1
  def destroy
    @design.destroy
    redirect_to designs_url, notice: 'Design was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_design
      @design = Design.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def design_params
      params.require(:design).permit(:name, :description)
    end
end

app/helpers/designs_helper.rb
module DesignsHelper
end

app/views/designs/_form.html.erb
<%= form_with(model: design, local: true) do |form| %>
  <% if design.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(design.errors.count, "error") %> prohibited this design from being saved:</h2>

      <ul>
      <% design.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/designs/edit.html.erb
<h1>Editing Design</h1>

<%= render 'form', design: @design %>

<%= link_to 'Show', @design %> |
<%= link_to 'Back', designs_path %>

app/views/designs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Designs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @designs.each do |design| %>
      <tr>
        <td><%= design.name %></td>
        <td><%= design.description %></td>
        <td><%= link_to 'Show', design %></td>
        <td><%= link_to 'Edit', edit_design_path(design) %></td>
        <td><%= link_to 'Destroy', design, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Design', new_design_path %>

app/views/designs/new.html.erb
<h1>New Design</h1>

<%= render 'form', design: @design %>

<%= link_to 'Back', designs_path %>

app/views/designs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @design.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @design.description %>
</p>

<%= link_to 'Edit', edit_design_path(@design) %> |
<%= link_to 'Back', designs_path %>