config/routes.rb
Rails.application.routes.draw do
  resources :material_brands
  resources :condition_details
  resources :templates
  resources :designs
  resources :colors
  resources :clothing_brands

  root 'main#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/material_brand.rb
class MaterialBrand < ApplicationRecord
end

app/controllers/material_brands_controller.rb
class MaterialBrandsController < ApplicationController
  before_action :set_material_brand, only: [:show, :edit, :update, :destroy]

  # GET /material_brands
  def index
    @material_brands = MaterialBrand.all
  end

  # GET /material_brands/1
  def show
    respond_to do |format|
      format.html { }
      format.json { render json: @material_brand }
    end
  end

  # GET /material_brands/new
  def new
    @material_brand = MaterialBrand.new
  end

  # GET /material_brands/1/edit
  def edit
  end

  # POST /material_brands
  def create
    @material_brand = MaterialBrand.new(material_brand_params)

    if @material_brand.save
      redirect_to @material_brand, notice: 'Material brand was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /material_brands/1
  def update
    if @material_brand.update(material_brand_params)
      redirect_to @material_brand, notice: 'Material brand was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /material_brands/1
  def destroy
    @material_brand.destroy
    redirect_to material_brands_url, notice: 'Material brand was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material_brand
      @material_brand = MaterialBrand.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def material_brand_params
      params.require(:material_brand).permit(:name, :description)
    end
end

app/helpers/material_brands_helper.rb
module MaterialBrandsHelper
end

app/views/material_brands/_form.html.erb
<%= form_with(model: material_brand, local: true) do |form| %>
  <% if material_brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(material_brand.errors.count, "error") %> prohibited this material_brand from being saved:</h2>

      <ul>
      <% material_brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/material_brands/edit.html.erb
<h1>Editing Material Brand</h1>

<%= render 'form', material_brand: @material_brand %>

<%= link_to 'Show', @material_brand %> |
<%= link_to 'Back', material_brands_path %>

app/views/material_brands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Material Brands</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @material_brands.each do |material_brand| %>
      <tr>
        <td><%= material_brand.name %></td>
        <td><%= material_brand.description %></td>
        <td><%= link_to 'Show', material_brand %></td>
        <td><%= link_to 'Edit', edit_material_brand_path(material_brand) %></td>
        <td><%= link_to 'Destroy', material_brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Material Brand', new_material_brand_path %>

app/views/material_brands/new.html.erb
<h1>New Material Brand</h1>

<%= render 'form', material_brand: @material_brand %>

<%= link_to 'Back', material_brands_path %>

app/views/material_brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @material_brand.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @material_brand.description %>
</p>

<%= link_to 'Edit', edit_material_brand_path(@material_brand) %> |
<%= link_to 'Back', material_brands_path %>