config/routes.rb
Rails.application.routes.draw do
  resources :material_brands
  resources :condition_details
  resources :templates
  resources :designs
  resources :colors
  resources :clothing_brands

  root 'main#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/condition_detail.rb
class ConditionDetail < ApplicationRecord
end

app/controllers/condition_details_controller.rb
class ConditionDetailsController < ApplicationController
  before_action :set_condition_detail, only: [:show, :edit, :update, :destroy]

  # GET /condition_details
  def index
    @condition_details = ConditionDetail.all
  end

  # GET /condition_details/1
  def show
  end

  # GET /condition_details/new
  def new
    @condition_detail = ConditionDetail.new
  end

  # GET /condition_details/1/edit
  def edit
  end

  # POST /condition_details
  def create
    @condition_detail = ConditionDetail.new(condition_detail_params)

    if @condition_detail.save
      redirect_to @condition_detail, notice: 'Condition detail was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /condition_details/1
  def update
    if @condition_detail.update(condition_detail_params)
      redirect_to @condition_detail, notice: 'Condition detail was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /condition_details/1
  def destroy
    @condition_detail.destroy
    redirect_to condition_details_url, notice: 'Condition detail was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_condition_detail
      @condition_detail = ConditionDetail.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def condition_detail_params
      params.require(:condition_detail).permit(:name, :description, :color_code, :tags)
    end
end

app/helpers/condition_details_helper.rb
module ConditionDetailsHelper
end

app/views/condition_details/_form.html.erb
<%= form_with(model: condition_detail, local: true) do |form| %>
  <% if condition_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(condition_detail.errors.count, "error") %> prohibited this condition_detail from being saved:</h2>

      <ul>
      <% condition_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :color_code %>
    <%= form.text_field :color_code %>
  </div>

  <div class="field">
    <%= form.label :tags %>
    <%= form.text_field :tags %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/condition_details/edit.html.erb
<h1>Editing Condition Detail</h1>

<%= render 'form', condition_detail: @condition_detail %>

<%= link_to 'Show', @condition_detail %> |
<%= link_to 'Back', condition_details_path %>

app/views/condition_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Condition Details</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Color code</th>
      <th>Tags</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @condition_details.each do |condition_detail| %>
      <tr>
        <td><%= condition_detail.name %></td>
        <td><%= condition_detail.description %></td>
        <td><%= condition_detail.color_code %></td>
        <td><%= condition_detail.tags %></td>
        <td><%= link_to 'Show', condition_detail %></td>
        <td><%= link_to 'Edit', edit_condition_detail_path(condition_detail) %></td>
        <td><%= link_to 'Destroy', condition_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Condition Detail', new_condition_detail_path %>

app/views/condition_details/new.html.erb
<h1>New Condition Detail</h1>

<%= render 'form', condition_detail: @condition_detail %>

<%= link_to 'Back', condition_details_path %>

app/views/condition_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @condition_detail.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @condition_detail.description %>
</p>

<p>
  <strong>Color code:</strong>
  <%= @condition_detail.color_code %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @condition_detail.tags %>
</p>

<%= link_to 'Edit', edit_condition_detail_path(@condition_detail) %> |
<%= link_to 'Back', condition_details_path %>